use clap::Command;

/*
    Includes the file generated by the build.rs script, which looks like:
    pub const GIT_COMMIT: &str = "c5f7034f79bc3d49c1a9fb81c7cac6a8a778c5c3";
*/
include!(concat!(env!("OUT_DIR"), "/git_commit.rs"));

fn main() {
    println!("starting main.rs script...");
    let app = Command::new("Version")
        .version(GIT_COMMIT) // Use the git commit hash as the version
        .about("This app explores outputting the git-commit (on a `--version` flag) via a build.rs script.");

    let _matches = app.get_matches();

    println!("Hello, world!");
}
